const PDFDocument = require('pdfkit');

async function generatePDF(reportData, category) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ margin: 40, size: 'A4' });

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).fillColor('#00E5FF').text('Schoolero ERP', { align: 'center' }).moveDown(0.5);
    doc.fontSize(14).fillColor('#111827').text(category || 'Report', { align: 'center' }).moveDown(0.5);
    doc
      .fontSize(9)
      .fillColor('#6B7280')
      .text(
        `Generated: ${new Date().toISOString()} | Tenant: ${reportData.tenantId || 'N/A'}`,
        { align: 'center' }
      )
      .moveDown(1);

    doc.moveTo(40, doc.y).lineTo(555, doc.y).strokeColor('#D1D5DB').stroke().moveDown(0.5);

    if (reportData.summary) {
      doc.fontSize(11).fillColor('#0EA5E9').text('Summary').moveDown(0.3);
      Object.entries(reportData.summary).forEach(([k, v]) => {
        doc.fontSize(9).fillColor('#4B5563').text(`${k}: ${String(v)}`);
      });
      doc.moveDown(0.5);
    }

    if (Array.isArray(reportData.data) && reportData.data.length > 0) {
      doc.fontSize(11).fillColor('#0EA5E9').text('Data').moveDown(0.3);
      reportData.data.slice(0, 50).forEach((row, i) => {
        doc.fontSize(8).fillColor(i % 2 === 0 ? '#6B7280' : '#111827').text(JSON.stringify(row).substring(0, 120));
      });
    }

    doc.moveDown(2);
    doc
      .fontSize(8)
      .fillColor('#6B7280')
      .text('Confidential report generated by Schoolero ERP Reporting Engine', { align: 'center' });

    doc.end();
  });
}

module.exports = { generatePDF };
