// Central model registration file

require('./School');
require('./User');
require('./Student');
require('./Parent');
require('./Teacher');
require('./Subject');
require('./Class');
require('./Section');
require('./AcademicSession');
require('./StudentDailyAttendance');
require('./StudentSubjectAttendance');
require('./TeacherAttendance');
require('./Exam');
require('./ExamForm');
require('./ExamPayment');
require('./AdmitCard');
require('./Result');
require('./FeeStructure');
require('./StudentFee');
require('./FeePayment');
require('./OnlinePayment');
require('./Expense');
require('./SalaryProfile');
require('./SalaryCalculation');
require('./SalaryPayment');
require('./Vehicle');
require('./Route');
require('./StudentTransport');
require('./Hostel');
require('./Room');
require('./StudentHostel');
require('./HostelLeave');
require('./Homework');
require('./tc');
require('./SystemAnnouncement');
require('./AuditLog');
require('./Backup'); // 🔴 THIS IS CRITICAL
